DROP TABLE IF EXISTS DELIVERY_ITEM;

CREATE TABLE DELIVERY_ITEM (
   ID      INTEGER  NOT NULL
  ,ITEM_NAME       VARCHAR(11) NOT NULL
  ,QUANTITY      INTEGER  NOT NULL
);

INSERT INTO DELIVERY_ITEM(ID,ITEM_NAME,QUANTITY) VALUES (1,'Item 1', 3);
INSERT INTO DELIVERY_ITEM(ID,ITEM_NAME,QUANTITY) VALUES (2,'Item 2', 30);
INSERT INTO DELIVERY_ITEM(ID,ITEM_NAME,QUANTITY) VALUES (3,'Item 3', 39);
INSERT INTO DELIVERY_ITEM(ID,ITEM_NAME,QUANTITY) VALUES (4,'Item 4', 38);
INSERT INTO DELIVERY_ITEM(ID,ITEM_NAME,QUANTITY) VALUES (5,'Item 5', 37);
INSERT INTO DELIVERY_ITEM(ID,ITEM_NAME,QUANTITY) VALUES (6,'Item 6', 36);
INSERT INTO DELIVERY_ITEM(ID,ITEM_NAME,QUANTITY) VALUES (7,'Item 7', 35);
INSERT INTO DELIVERY_ITEM(ID,ITEM_NAME,QUANTITY) VALUES (8,'Item 8', 34);
INSERT INTO DELIVERY_ITEM(ID,ITEM_NAME,QUANTITY) VALUES (9,'Item 9', 33);
INSERT INTO DELIVERY_ITEM(ID,ITEM_NAME,QUANTITY) VALUES (10,'Item 10', 32);
INSERT INTO DELIVERY_ITEM(ID,ITEM_NAME,QUANTITY) VALUES (11,'Item 11', 31);
